# Generated by Django 3.2.18 on 2023-07-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230725_2342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffPrice',
            new_name='ShopkeeperPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='staff_price',
        ),
        migrations.AlterField(
            model_name='shopkeeperprice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
    ]
