# Generated by Django 3.2.18 on 2023-07-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_shopkeeperprice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
